type: influxdb
version: 2
name: influxdb2-energydata
host: localhost
port: 18086
org: tspilot
bucket: energydata
database: energydata
token: tspilot-dev-token
username: tspilot
password: tspilot_password
ssl_enabled: false
max_connections: 10
schema_measurement_names:
  - home_energy_environment
